library(ggplot2)
library(parsedate)
library(tidyr)
library(sqldf)
library(grid)
library(gridExtra)

require("RPostgreSQL")
drv = dbDriver("PostgreSQL")
con = NULL
if(is.null(con)) {
   con = dbConnect(drv, dbname = "snowset",
                   host = "127.0.0.1", port = 25432,
                   user = "postgres")
}

# -----------------------------------------------------------------------------
# For all queries
# -----------------------------------------------------------------------------

qres = dbGetQuery(con, paste("
select 'count' as res, 'all' as wtype, sum(case when profScanRso >= profScanRso and profScanRso >= profXtScanRso and profScanRso >= profProjRso and profScanRso >= profSortRso and profScanRso >= profFilterRso and profScanRso >= profResRso and profScanRso >= profDmlRso and profScanRso >= profHjRso and profScanRso >= profBufRso and profScanRso >= profFlatRso and profScanRso >= profBloomRso and profScanRso >= profAggRso then 1 else 0 end) as scan,
       sum(case when profXtScanRso >= profScanRso and profXtScanRso >= profXtScanRso and profXtScanRso >= profProjRso and profXtScanRso >= profSortRso and profXtScanRso >= profFilterRso and profXtScanRso >= profResRso and profXtScanRso >= profDmlRso and profXtScanRso >= profHjRso and profXtScanRso >= profBufRso and profXtScanRso >= profFlatRso and profXtScanRso >= profBloomRso and profXtScanRso >= profAggRso then 1 else 0 end) as xtscan,
       sum(case when profProjRso >= profScanRso and profProjRso >= profXtScanRso and profProjRso >= profProjRso and profProjRso >= profSortRso and profProjRso >= profFilterRso and profProjRso >= profResRso and profProjRso >= profDmlRso and profProjRso >= profHjRso and profProjRso >= profBufRso and profProjRso >= profFlatRso and profProjRso >= profBloomRso and profProjRso >= profAggRso then 1 else 0 end) as proj,
       sum(case when profSortRso >= profScanRso and profSortRso >= profXtScanRso and profSortRso >= profProjRso and profSortRso >= profSortRso and profSortRso >= profFilterRso and profSortRso >= profResRso and profSortRso >= profDmlRso and profSortRso >= profHjRso and profSortRso >= profBufRso and profSortRso >= profFlatRso and profSortRso >= profBloomRso and profSortRso >= profAggRso then 1 else 0 end) as sort,
       sum(case when profFilterRso >= profScanRso and profFilterRso >= profXtScanRso and profFilterRso >= profProjRso and profFilterRso >= profSortRso and profFilterRso >= profFilterRso and profFilterRso >= profResRso and profFilterRso >= profDmlRso and profFilterRso >= profHjRso and profFilterRso >= profBufRso and profFilterRso >= profFlatRso and profFilterRso >= profBloomRso and profFilterRso >= profAggRso then 1 else 0 end) as filter,
       sum(case when profResRso >= profScanRso and profResRso >= profXtScanRso and profResRso >= profProjRso and profResRso >= profSortRso and profResRso >= profFilterRso and profResRso >= profResRso and profResRso >= profDmlRso and profResRso >= profHjRso and profResRso >= profBufRso and profResRso >= profFlatRso and profResRso >= profBloomRso and profResRso >= profAggRso then 1 else 0 end) as result,
       sum(case when profDmlRso >= profScanRso and profDmlRso >= profXtScanRso and profDmlRso >= profProjRso and profDmlRso >= profSortRso and profDmlRso >= profFilterRso and profDmlRso >= profResRso and profDmlRso >= profDmlRso and profDmlRso >= profHjRso and profDmlRso >= profBufRso and profDmlRso >= profFlatRso and profDmlRso >= profBloomRso and profDmlRso >= profAggRso then 1 else 0 end) as dml,
       sum(case when profHjRso >= profScanRso and profHjRso >= profXtScanRso and profHjRso >= profProjRso and profHjRso >= profSortRso and profHjRso >= profFilterRso and profHjRso >= profResRso and profHjRso >= profDmlRso and profHjRso >= profHjRso and profHjRso >= profBufRso and profHjRso >= profFlatRso and profHjRso >= profBloomRso and profHjRso >= profAggRso then 1 else 0 end) as hjoin,
       sum(case when profBufRso >= profScanRso and profBufRso >= profXtScanRso and profBufRso >= profProjRso and profBufRso >= profSortRso and profBufRso >= profFilterRso and profBufRso >= profResRso and profBufRso >= profDmlRso and profBufRso >= profHjRso and profBufRso >= profBufRso and profBufRso >= profFlatRso and profBufRso >= profBloomRso and profBufRso >= profAggRso then 1 else 0 end) as buffer,
       sum(case when profBloomRso >= profScanRso and profBloomRso >= profXtScanRso and profBloomRso >= profProjRso and profBloomRso >= profSortRso and profBloomRso >= profFilterRso and profBloomRso >= profResRso and profBloomRso >= profDmlRso and profBloomRso >= profHjRso and profBloomRso >= profBufRso and profBloomRso >= profFlatRso and profBloomRso >= profBloomRso and profBloomRso >= profAggRso then 1 else 0 end) as bloom,
       sum(case when profAggRso >= profScanRso and profAggRso >= profXtScanRso and profAggRso >= profProjRso and profAggRso >= profSortRso and profAggRso >= profFilterRso and profAggRso >= profResRso and profAggRso >= profDmlRso and profAggRso >= profHjRso and profAggRso >= profBufRso and profAggRso >= profFlatRso and profAggRso >= profBloomRso and profAggRso >= profAggRso then 1 else 0 end) as agg
from with_7
where wtype <> 'nothing'
union all
select 'time' as res, 'all' as wtype, sum(case when profScanRso >= profScanRso and profScanRso >= profXtScanRso and profScanRso >= profProjRso and profScanRso >= profSortRso and profScanRso >= profFilterRso and profScanRso >= profResRso and profScanRso >= profDmlRso and profScanRso >= profHjRso and profScanRso >= profBufRso and profScanRso >= profFlatRso and profScanRso >= profBloomRso and profScanRso >= profAggRso then cputime else 0 end) as scan,
       sum(case when profXtScanRso >= profScanRso and profXtScanRso >= profXtScanRso and profXtScanRso >= profProjRso and profXtScanRso >= profSortRso and profXtScanRso >= profFilterRso and profXtScanRso >= profResRso and profXtScanRso >= profDmlRso and profXtScanRso >= profHjRso and profXtScanRso >= profBufRso and profXtScanRso >= profFlatRso and profXtScanRso >= profBloomRso and profXtScanRso >= profAggRso then cputime else 0 end) as xtscan,
       sum(case when profProjRso >= profScanRso and profProjRso >= profXtScanRso and profProjRso >= profProjRso and profProjRso >= profSortRso and profProjRso >= profFilterRso and profProjRso >= profResRso and profProjRso >= profDmlRso and profProjRso >= profHjRso and profProjRso >= profBufRso and profProjRso >= profFlatRso and profProjRso >= profBloomRso and profProjRso >= profAggRso then cputime else 0 end) as proj,
       sum(case when profSortRso >= profScanRso and profSortRso >= profXtScanRso and profSortRso >= profProjRso and profSortRso >= profSortRso and profSortRso >= profFilterRso and profSortRso >= profResRso and profSortRso >= profDmlRso and profSortRso >= profHjRso and profSortRso >= profBufRso and profSortRso >= profFlatRso and profSortRso >= profBloomRso and profSortRso >= profAggRso then cputime else 0 end) as sort,
       sum(case when profFilterRso >= profScanRso and profFilterRso >= profXtScanRso and profFilterRso >= profProjRso and profFilterRso >= profSortRso and profFilterRso >= profFilterRso and profFilterRso >= profResRso and profFilterRso >= profDmlRso and profFilterRso >= profHjRso and profFilterRso >= profBufRso and profFilterRso >= profFlatRso and profFilterRso >= profBloomRso and profFilterRso >= profAggRso then cputime else 0 end) as filter,
       sum(case when profResRso >= profScanRso and profResRso >= profXtScanRso and profResRso >= profProjRso and profResRso >= profSortRso and profResRso >= profFilterRso and profResRso >= profResRso and profResRso >= profDmlRso and profResRso >= profHjRso and profResRso >= profBufRso and profResRso >= profFlatRso and profResRso >= profBloomRso and profResRso >= profAggRso then cputime else 0 end) as result,
       sum(case when profDmlRso >= profScanRso and profDmlRso >= profXtScanRso and profDmlRso >= profProjRso and profDmlRso >= profSortRso and profDmlRso >= profFilterRso and profDmlRso >= profResRso and profDmlRso >= profDmlRso and profDmlRso >= profHjRso and profDmlRso >= profBufRso and profDmlRso >= profFlatRso and profDmlRso >= profBloomRso and profDmlRso >= profAggRso then cputime else 0 end) as dml,
       sum(case when profHjRso >= profScanRso and profHjRso >= profXtScanRso and profHjRso >= profProjRso and profHjRso >= profSortRso and profHjRso >= profFilterRso and profHjRso >= profResRso and profHjRso >= profDmlRso and profHjRso >= profHjRso and profHjRso >= profBufRso and profHjRso >= profFlatRso and profHjRso >= profBloomRso and profHjRso >= profAggRso then cputime else 0 end) as hjoin,
       sum(case when profBufRso >= profScanRso and profBufRso >= profXtScanRso and profBufRso >= profProjRso and profBufRso >= profSortRso and profBufRso >= profFilterRso and profBufRso >= profResRso and profBufRso >= profDmlRso and profBufRso >= profHjRso and profBufRso >= profBufRso and profBufRso >= profFlatRso and profBufRso >= profBloomRso and profBufRso >= profAggRso then cputime else 0 end) as buffer,
       sum(case when profBloomRso >= profScanRso and profBloomRso >= profXtScanRso and profBloomRso >= profProjRso and profBloomRso >= profSortRso and profBloomRso >= profFilterRso and profBloomRso >= profResRso and profBloomRso >= profDmlRso and profBloomRso >= profHjRso and profBloomRso >= profBufRso and profBloomRso >= profFlatRso and profBloomRso >= profBloomRso and profBloomRso >= profAggRso then cputime else 0 end) as bloom,
       sum(case when profAggRso >= profScanRso and profAggRso >= profXtScanRso and profAggRso >= profProjRso and profAggRso >= profSortRso and profAggRso >= profFilterRso and profAggRso >= profResRso and profAggRso >= profDmlRso and profAggRso >= profHjRso and profAggRso >= profBufRso and profAggRso >= profFlatRso and profAggRso >= profBloomRso and profAggRso >= profAggRso then cputime else 0 end) as agg
from with_7
where wtype <> 'nothing'
union all
select 'count' as res, wtype, sum(case when profScanRso >= profScanRso and profScanRso >= profXtScanRso and profScanRso >= profProjRso and profScanRso >= profSortRso and profScanRso >= profFilterRso and profScanRso >= profResRso and profScanRso >= profDmlRso and profScanRso >= profHjRso and profScanRso >= profBufRso and profScanRso >= profFlatRso and profScanRso >= profBloomRso and profScanRso >= profAggRso then 1 else 0 end) as scan,
       sum(case when profXtScanRso >= profScanRso and profXtScanRso >= profXtScanRso and profXtScanRso >= profProjRso and profXtScanRso >= profSortRso and profXtScanRso >= profFilterRso and profXtScanRso >= profResRso and profXtScanRso >= profDmlRso and profXtScanRso >= profHjRso and profXtScanRso >= profBufRso and profXtScanRso >= profFlatRso and profXtScanRso >= profBloomRso and profXtScanRso >= profAggRso then 1 else 0 end) as xtscan,
       sum(case when profProjRso >= profScanRso and profProjRso >= profXtScanRso and profProjRso >= profProjRso and profProjRso >= profSortRso and profProjRso >= profFilterRso and profProjRso >= profResRso and profProjRso >= profDmlRso and profProjRso >= profHjRso and profProjRso >= profBufRso and profProjRso >= profFlatRso and profProjRso >= profBloomRso and profProjRso >= profAggRso then 1 else 0 end) as proj,
       sum(case when profSortRso >= profScanRso and profSortRso >= profXtScanRso and profSortRso >= profProjRso and profSortRso >= profSortRso and profSortRso >= profFilterRso and profSortRso >= profResRso and profSortRso >= profDmlRso and profSortRso >= profHjRso and profSortRso >= profBufRso and profSortRso >= profFlatRso and profSortRso >= profBloomRso and profSortRso >= profAggRso then 1 else 0 end) as sort,
       sum(case when profFilterRso >= profScanRso and profFilterRso >= profXtScanRso and profFilterRso >= profProjRso and profFilterRso >= profSortRso and profFilterRso >= profFilterRso and profFilterRso >= profResRso and profFilterRso >= profDmlRso and profFilterRso >= profHjRso and profFilterRso >= profBufRso and profFilterRso >= profFlatRso and profFilterRso >= profBloomRso and profFilterRso >= profAggRso then 1 else 0 end) as filter,
       sum(case when profResRso >= profScanRso and profResRso >= profXtScanRso and profResRso >= profProjRso and profResRso >= profSortRso and profResRso >= profFilterRso and profResRso >= profResRso and profResRso >= profDmlRso and profResRso >= profHjRso and profResRso >= profBufRso and profResRso >= profFlatRso and profResRso >= profBloomRso and profResRso >= profAggRso then 1 else 0 end) as result,
       sum(case when profDmlRso >= profScanRso and profDmlRso >= profXtScanRso and profDmlRso >= profProjRso and profDmlRso >= profSortRso and profDmlRso >= profFilterRso and profDmlRso >= profResRso and profDmlRso >= profDmlRso and profDmlRso >= profHjRso and profDmlRso >= profBufRso and profDmlRso >= profFlatRso and profDmlRso >= profBloomRso and profDmlRso >= profAggRso then 1 else 0 end) as dml,
       sum(case when profHjRso >= profScanRso and profHjRso >= profXtScanRso and profHjRso >= profProjRso and profHjRso >= profSortRso and profHjRso >= profFilterRso and profHjRso >= profResRso and profHjRso >= profDmlRso and profHjRso >= profHjRso and profHjRso >= profBufRso and profHjRso >= profFlatRso and profHjRso >= profBloomRso and profHjRso >= profAggRso then 1 else 0 end) as hjoin,
       sum(case when profBufRso >= profScanRso and profBufRso >= profXtScanRso and profBufRso >= profProjRso and profBufRso >= profSortRso and profBufRso >= profFilterRso and profBufRso >= profResRso and profBufRso >= profDmlRso and profBufRso >= profHjRso and profBufRso >= profBufRso and profBufRso >= profFlatRso and profBufRso >= profBloomRso and profBufRso >= profAggRso then 1 else 0 end) as buffer,
       sum(case when profBloomRso >= profScanRso and profBloomRso >= profXtScanRso and profBloomRso >= profProjRso and profBloomRso >= profSortRso and profBloomRso >= profFilterRso and profBloomRso >= profResRso and profBloomRso >= profDmlRso and profBloomRso >= profHjRso and profBloomRso >= profBufRso and profBloomRso >= profFlatRso and profBloomRso >= profBloomRso and profBloomRso >= profAggRso then 1 else 0 end) as bloom,
       sum(case when profAggRso >= profScanRso and profAggRso >= profXtScanRso and profAggRso >= profProjRso and profAggRso >= profSortRso and profAggRso >= profFilterRso and profAggRso >= profResRso and profAggRso >= profDmlRso and profAggRso >= profHjRso and profAggRso >= profBufRso and profAggRso >= profFlatRso and profAggRso >= profBloomRso and profAggRso >= profAggRso then 1 else 0 end) as agg
from with_7
where wtype <> 'nothing'
group by wtype
union all
select 'time' as res, wtype, sum(case when profScanRso >= profScanRso and profScanRso >= profXtScanRso and profScanRso >= profProjRso and profScanRso >= profSortRso and profScanRso >= profFilterRso and profScanRso >= profResRso and profScanRso >= profDmlRso and profScanRso >= profHjRso and profScanRso >= profBufRso and profScanRso >= profFlatRso and profScanRso >= profBloomRso and profScanRso >= profAggRso then cputime else 0 end) as scan,
       sum(case when profXtScanRso >= profScanRso and profXtScanRso >= profXtScanRso and profXtScanRso >= profProjRso and profXtScanRso >= profSortRso and profXtScanRso >= profFilterRso and profXtScanRso >= profResRso and profXtScanRso >= profDmlRso and profXtScanRso >= profHjRso and profXtScanRso >= profBufRso and profXtScanRso >= profFlatRso and profXtScanRso >= profBloomRso and profXtScanRso >= profAggRso then cputime else 0 end) as xtscan,
       sum(case when profProjRso >= profScanRso and profProjRso >= profXtScanRso and profProjRso >= profProjRso and profProjRso >= profSortRso and profProjRso >= profFilterRso and profProjRso >= profResRso and profProjRso >= profDmlRso and profProjRso >= profHjRso and profProjRso >= profBufRso and profProjRso >= profFlatRso and profProjRso >= profBloomRso and profProjRso >= profAggRso then cputime else 0 end) as proj,
       sum(case when profSortRso >= profScanRso and profSortRso >= profXtScanRso and profSortRso >= profProjRso and profSortRso >= profSortRso and profSortRso >= profFilterRso and profSortRso >= profResRso and profSortRso >= profDmlRso and profSortRso >= profHjRso and profSortRso >= profBufRso and profSortRso >= profFlatRso and profSortRso >= profBloomRso and profSortRso >= profAggRso then cputime else 0 end) as sort,
       sum(case when profFilterRso >= profScanRso and profFilterRso >= profXtScanRso and profFilterRso >= profProjRso and profFilterRso >= profSortRso and profFilterRso >= profFilterRso and profFilterRso >= profResRso and profFilterRso >= profDmlRso and profFilterRso >= profHjRso and profFilterRso >= profBufRso and profFilterRso >= profFlatRso and profFilterRso >= profBloomRso and profFilterRso >= profAggRso then cputime else 0 end) as filter,
       sum(case when profResRso >= profScanRso and profResRso >= profXtScanRso and profResRso >= profProjRso and profResRso >= profSortRso and profResRso >= profFilterRso and profResRso >= profResRso and profResRso >= profDmlRso and profResRso >= profHjRso and profResRso >= profBufRso and profResRso >= profFlatRso and profResRso >= profBloomRso and profResRso >= profAggRso then cputime else 0 end) as result,
       sum(case when profDmlRso >= profScanRso and profDmlRso >= profXtScanRso and profDmlRso >= profProjRso and profDmlRso >= profSortRso and profDmlRso >= profFilterRso and profDmlRso >= profResRso and profDmlRso >= profDmlRso and profDmlRso >= profHjRso and profDmlRso >= profBufRso and profDmlRso >= profFlatRso and profDmlRso >= profBloomRso and profDmlRso >= profAggRso then cputime else 0 end) as dml,
       sum(case when profHjRso >= profScanRso and profHjRso >= profXtScanRso and profHjRso >= profProjRso and profHjRso >= profSortRso and profHjRso >= profFilterRso and profHjRso >= profResRso and profHjRso >= profDmlRso and profHjRso >= profHjRso and profHjRso >= profBufRso and profHjRso >= profFlatRso and profHjRso >= profBloomRso and profHjRso >= profAggRso then cputime else 0 end) as hjoin,
       sum(case when profBufRso >= profScanRso and profBufRso >= profXtScanRso and profBufRso >= profProjRso and profBufRso >= profSortRso and profBufRso >= profFilterRso and profBufRso >= profResRso and profBufRso >= profDmlRso and profBufRso >= profHjRso and profBufRso >= profBufRso and profBufRso >= profFlatRso and profBufRso >= profBloomRso and profBufRso >= profAggRso then cputime else 0 end) as buffer,
       sum(case when profBloomRso >= profScanRso and profBloomRso >= profXtScanRso and profBloomRso >= profProjRso and profBloomRso >= profSortRso and profBloomRso >= profFilterRso and profBloomRso >= profResRso and profBloomRso >= profDmlRso and profBloomRso >= profHjRso and profBloomRso >= profBufRso and profBloomRso >= profFlatRso and profBloomRso >= profBloomRso and profBloomRso >= profAggRso then cputime else 0 end) as bloom,
       sum(case when profAggRso >= profScanRso and profAggRso >= profXtScanRso and profAggRso >= profProjRso and profAggRso >= profSortRso and profAggRso >= profFilterRso and profAggRso >= profResRso and profAggRso >= profDmlRso and profAggRso >= profHjRso and profAggRso >= profBufRso and profAggRso >= profFlatRso and profAggRso >= profBloomRso and profAggRso >= profAggRso then cputime else 0 end) as agg
from with_7
where wtype <> 'nothing'
group by wtype;
"))

df = gather(qres, operator, value, scan:agg, factor_key=TRUE)
df = sqldf("select * from df where operator <> 'buffer'");

ggplot(df, aes(y=value, x=operator, label=operator, fill=operator)) +
   geom_col(position = "dodge") +
   geom_text(aes(label = operator), colour = "black", position = position_stack(vjust = 0.5)) +
   scale_fill_brewer(palette="Paired") +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + theme(legend.position = "none") +
   facet_grid(res ~ wtype, scales = "free") + 
   labs(y="CPU days", x="All Warehouses", fill = "Operator", title = "Operator Usage") + theme(plot.title = element_text(hjust = 0.5))

ggsave("dominant-operators-all.pdf", plot = last_plot(), scale = 1, units = c("in", "cm", "mm", "px"))
